version: '3'
services:
  airflow-webserver:
    image: apache/airflow
    container_name: airflow_webserver
    restart: always
    command: webserver
    ports:
      - 8080:8080
    environment:
      - LOAD_EX=n
      - FERNET_KEY=myfernetkey
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
