# Use an official Python runtime as a parent image
FROM python:latest

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /gns_app



# Install dependencies
COPY requirements.txt /gns_app
RUN pip install --no-cache-dir -r requirements.txt

# Copy project
COPY . /gns_app
